# app/models/note.py
# AI-generated structured notes per class
# Generated by Gemini from transcript, reviewed and approved by teacher

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, Enum, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.db.base_class import Base


class Note(Base):
    """
    Structured notes generated by Gemini 2.5 Flash from the class transcript.
    One note per class — published after teacher review.

    JSON structure stored in `content` field:
    {
        "summary": "3-4 sentence class summary",
        "key_points": ["Point 1", "Point 2", ...],
        "detailed_notes": "Full markdown notes",
        "qa_pairs": [{"q": "...", "a": "..."}],
        "topics_covered": ["Integration", "LIATE rule"]
    }

    Access rule: Only subscribed students and the class teacher can view notes.
    """
    __tablename__ = "notes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    class_id = Column(
        UUID(as_uuid=True),
        ForeignKey("classes.id", ondelete="CASCADE"),
        unique=True,                  # One note per class
        nullable=False,
        index=True,
    )
    transcript_id = Column(
        UUID(as_uuid=True),
        ForeignKey("transcripts.id", ondelete="SET NULL"),
        nullable=True,
    )

    # ── Content ───────────────────────────────────────────────────────────────
    content = Column(JSONB, nullable=True)                    # Structured JSON (see above)
    markdown_export = Column(Text, nullable=True)             # Flat markdown for download

    # ── Pipeline Status ───────────────────────────────────────────────────────
    status = Column(
        Enum(
            "generating",  # Gemini job in progress
            "draft",       # Generated, awaiting teacher review
            "published",   # Teacher approved → visible to subscribed students
            "failed",      # Generation failed
            name="note_status_enum",
        ),
        nullable=False,
        default="generating",
        index=True,
    )
    error_message = Column(Text, nullable=True)

    # ── Teacher Review ────────────────────────────────────────────────────────
    reviewed_by_teacher = Column(Boolean, nullable=False, default=False)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    teacher_edit_notes = Column(Text, nullable=True)          # Teacher's comments/edits

    # ── Embedding Status ──────────────────────────────────────────────────────
    # After publication, content is chunked and embedded for RAG (AI Tutor)
    embeddings_generated = Column(Boolean, nullable=False, default=False)

    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    published_at = Column(DateTime(timezone=True), nullable=True)

    # ── Relationships ─────────────────────────────────────────────────────────
    class_ = relationship("Class", back_populates="note")
    embeddings = relationship(
        "ContentEmbedding",
        back_populates="note",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Note class={self.class_id} status={self.status}>"